/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_replaymaster_ReplayMaster */

#ifndef _Included_me_replaymaster_ReplayMaster
#define _Included_me_replaymaster_ReplayMaster
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_replaymaster_ReplayMaster
 * Method:    nativeRender
 * Signature: (IILjava/lang/String;ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_me_replaymaster_ReplayMaster_nativeRender
  (JNIEnv *, jclass, jint, jint, jstring, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
